- package.json
> ✅ Update : 명령어 수정

- src/app/layout.tsx
> 🐛 Fix : 헤더, 푸터 위치변경

- src/app/drink/[id]/page.tsx
- src/app/mypage/page.tsx
> ✨ Feat : 주류 디테일페이지 UI 

- src/app/mypage/_components/ProfileEditModal.tsx
넥스트 이미지 컴포넌트로 바꿨습니다.
---
---
이미지 최적화를 위해 사용했습니다.
---
---
라이트하우스 테스트를 위해 코드는 재수정할 예정입니다.
---
> 🩹 Fix : 이미지 컴포넌트 수정.

- src/app/drink/[id]/page.tsx
- src/app/drink/_components/DrinkDetail.tsx
- src/app/drink/_components/FoodPairing.tsx
- src/app/drink/_components/ReviewSection.tsx
- src/app/drink/page.tsx
- src/types/supabase.ts
- src/utils/drink/action.ts
- src/utils/foodpairing/action.ts
주류, 추천음식 상세정보 렌더링
---
---
- 주류 상세정보 렌더링
- 주류 이름 밑에 짧은 설명 추가 및 UI 변경
- 해당 주류와 연동된 추천음식 3가지 렌더링
---
---
- 수파베이스 drinks 테이블 변경했습니다. genTypes 돌려주세요.
---
> ✨ Feat : 주류, 추천음식 상세정보 렌더링

- src/app/layout.tsx
- src/components/common/ScrollTop.tsx
✨ Feat : ScrollTop 기능추가
---
---
모바일 및 웹 환경에서 무한스크롤을 구현해야하기 때문에
스크롤 탑 기능 꼭 필요하다고 느끼기 때문에 구현했습니다.
---
---
루트 레이아웃에 포함시켰기 때문에,
다른 분들께서는 이 기능을 구현하지 않으셔도 됩니다.
---
> ✨ Feat : ScrollTop 기능추가

- src/app/survey/_components/PreferenceAcidity.tsx
- src/app/survey/_components/PreferenceAlcoholLevel.tsx
- src/app/survey/_components/PreferenceBody.tsx
- src/app/survey/_components/PreferenceCarbonation.tsx
- src/app/survey/_components/PreferenceFood.tsx
- src/app/survey/_components/PreferenceSweetness.tsx
- src/app/survey/_components/PreferenceTypeSelection.tsx
- src/app/survey/_components/Step.tsx
- src/app/survey/page.tsx
- src/components/layout/Footer.tsx
취향조사 퍼널패턴 구현과 푸터 부분 수정
---
---
취향조사는 ui 다 했고, 입력된 데이터까지 전체적으로 잘 나오는지 확인했습니다.
취향조사 페이지는 푸터가 안들어가는게 맞아서, layout에 있는 푸터 부분만 코드 수정했습니다
---
- [] 예시) 관련 문서를 업데이트했습니다.
---
레이아웃 푸터 부분 수정했으니깐 참고해주세요
---
> 취향조사 퍼널 패턴구현

- src/app/survey/_components/OptionItem.tsx
- src/app/survey/_components/PreferenceAcidity.tsx
- src/app/survey/_components/PreferenceAlcoholLevel.tsx
- src/app/survey/_components/PreferenceBody.tsx
- src/app/survey/_components/PreferenceCarbonation.tsx
- src/app/survey/_components/PreferenceFood.tsx
- src/app/survey/_components/PreferenceSweetness.tsx
- src/app/survey/_components/PreferenceTypeSelection.tsx
- src/app/survey/_components/ProgressBar.tsx
- src/app/survey/_components/StepButton.tsx
- src/app/survey/page.tsx
리팩토링: ActionButton 및 OptionItem 컴포넌트 분리로 코드 재사용성 향상
---
ProgressBar 컴포넌트 생성: 진행바 분리
ActionButton 컴포넌트 생성: 버튼 로직과 스타일링 분리
OptionItem 컴포넌트 생성: 옵션 렌더링 로직 및 스타일링 분리
PreferenceAcidity 및 PreferenceAlcoholLevel에서 중복된 버튼 및 옵션 렌더링 코드 제거
코드 재사용성 및 가독성 개선
- [] 주요 기능 추가/수정
---
공통 로직을 재사용 가능한 컴포넌트로 추출하여 코드 중복을 제거하고, 가독성과 유지보수성을 개선.
설문 단계에서 사용되는 모든 버튼과 옵션을 통일된 스타일과 로직으로 관리하기 위함.
---
---
---
> Refactor:  ActionButton 및 OptionItem 컴포넌트 분리로 코드 재사용성 향상

- src/utils/foodpairing/action.ts
🐛 Bug : 푸드페어링 서버액션 타입오류
---
---
병합 후 푸드페어링 서버액션에서 
리턴값이 타입오류가 나던것을 수정했습니다.
---
---
딱히 없어용.
---
> 🐛 Bug : 푸드페어링 서버액션 타입오류

- src/app/drink/_components/ReviewEditingContent.tsx
💄 Style : 수정하기 인풋박스 CSS수정
---
---
수정하기 인풋창에서 focus했을때, border부분이 겹쳐보이는 현상을 발견해서 수정했습니다.
---
---
없습니다.
---
> 💄 Style : 수정하기 인풋박스 CSS수정

- src/types/supabase.ts
⚰️ Chore : 테이블 구조변경에 따른 yarn genTypes 실행
---
---
테이블 구조변경에 따른 타입변경입니다!
yarn genTypes 굳이 안하셔도 됩니다.
---
---
혹시 불안하시면 yarn genTypes 한 번 해보세요.
---
> ⚰️ Chore : 테이블 구조변경에 따른 yarn genTypes 실행

- package.json
- src/app/drink/_components/DrinkDescription.tsx
- src/app/drink/_components/DynamicHeader.tsx
- src/app/layout.tsx
- src/components/common/LikeButton.tsx
- src/providers/ToastProvider.tsx
- src/styles/toast-custom.css
- yarn.lock
✨ Feat : 토스트 알림창 구현
---
---
1. 좋아요 추가/제거 알림창 구현
2. 토스트 알림 임시로 커스텀
3. 500 Error 해결 : user?.id로 해결
➡️ 왜 자꾸 뜨나했는데 유저 객체가 없을때 나는 에러더라구요. 지금은 해결했습니다.
---
---
1. 토스티파이 라이브러리 설치 했습니다. yarn 한 번 돌리세요.
---
> ✨ Feat : 토스트 알림창 구현

- src/app/mypage/_components/MyPageComponent.tsx
- src/app/mypage/page.tsx
- src/hooks/mypage/useMyPage.ts
- src/hooks/mypage/useProfileEdit.ts
- src/utils/mypage/action.ts
🐛 Bug : 프로필 수정 후 리렌더링 안되는부분 수정
---
---
코드 리팩토링 후 프로필 수정했을때 리렌더링이 안되는 부분을 수정했습니다.
---
---
- 마이페이지를 서버 컴포넌트로 만들면서 최초로 유저데이터를 불러오는 로직때문이었습니다.
- 수정 후 잘됩니다.
---
> 🐛 Bug : 프로필 수정 후 리렌더링 안되는부분 수정

- src/app/page.tsx
- src/components/auth/UserInitializer.tsx
- src/components/layout/Header.tsx
- src/hooks/auth/useSignIn.ts
- src/utils/auth/action.ts
사용자 정보 저장 로직 보완
---
---
- 기존에는 로그인 성공 시 사용자 정보를 저장하는 로직을 Header 컴포넌트에서 실행
- 사용자 정보를 저장하는 로직을 처리하기 위한 컴포넌트 UserInitializer 생성
---
---
utils/mypage/action.ts에 있는 getUserProfile 대신 utils/auth/action.js에 있는 fetchUser 사용하시면 될 것 같습니다.
---
> 사용자 정보 저장 로직 보완

- src/app/layout.tsx
- src/app/page.tsx
- src/components/common/BottomNavBar.tsx
- src/components/common/DiningBarCard.tsx
- src/components/common/LikeButton.tsx
- src/components/common/MockSection.tsx
- src/components/common/ProductCard.tsx
- src/styles/globals.css
✨ Feat : 공통 컴포넌트 구현
---
---
1. 바텀 네비바 구현했습니다. (주류 상세정보에는 안나옵니다.)
2. 목 데이터 하나 추가해서 홈 페이지에 잠시 끼워놨습니다. (차후 수정)
3. 다이닝바 카드 임시로 만들어놨습니다.
4. 스크롤바 커스텀 했습니다. (모바일에서는 아직 못함)
---
---
- 바텀 네비바에 좋아요는 링크를 임시로 해놓았습니다. 나중에 바꿔주세요.
- 모바일 환경에서 좋아요 버튼 너무 크면 나중에 수정하겠습니다.
---
> ✨ Feat : 공통 컴포넌트 구현

- src/app/drink/_components/DrinkDescription.tsx
- src/app/mypage/page.tsx
- src/hooks/mypage/useMyPage.ts
- src/utils/mypage/action.ts
♻️ Refactor : fetchUser 함수로 통일
---
---
- fetchUser함수로 통일시켰습니다
- DrinkDescription.tsx 서버 컴포넌트로 변경되었습니다.
---
---
없어용
---
> ♻️ Refactor : fetchUser 함수로 통일

- package.json
- src/components/common/BottomNavBar.tsx
- src/components/common/MockSection.tsx
- src/components/common/ProductCard.tsx
- yarn.lock
✨ Feat : 홈 페이지 UI 구현
---
---
1. Swiper 설치했습니다.
2. Link 태그 안쪽에 a 태그 있어서 오류가 발생해 수정했습니다.
3. 홈 페이지 UI 구성해봤습니다.
---
---
- 라이브러리 설치했으니, 풀 받으신 후에 yarn 한 번 해주세요.
---
> ✨ Feat : 홈 페이지 UI 구현

- src/app/signin/_components/Social.tsx
- src/app/signup/_components/Terms.tsx
- src/components/auth/UserInitializer.tsx
- src/hooks/auth/useSocial.tsx
- src/store/authStore.ts
- src/types/supabase.ts
- src/utils/auth/action.ts
- src/utils/supabase/middleware.ts
소셜 로그인에 이용약관 동의 연동
---
---
- 처음 서비스를 이용하는 사용자가 로그인 페이지에서 바로 소셜 로그인을 할 경우, 이용약관 동의 과정을 건너뛰게됨
- users 테이블에 이용약관 동의 여부를 보여주는 데이터 agree_terms 추가
- 이용약관 동의를 하지 않은 소셜 사용자인 경우, 이용약관 동의 페이지로 redirect
---
---
- 가입되지 않은 소셜 계정으로 로그인 페이지에서 소셜 로그인을 할 경우 이용약관 동의 페이지로 잘 이동하는지 확인 부탁드립니다.
---
> 소셜 로그인에 이용약관 동의 연동

- src/app/drink/_components/ReviewList.tsx
- src/app/drink/_components/ReviewSection.tsx
- src/hooks/review/useReviewActions.ts
- src/types/review.ts
- src/utils/review/action.ts
✨ Feat : 리뷰 무한스크롤 구현
---
---
- 리뷰 무한스크롤 구현했습니다.
---
---
- 무한 스크롤은 "drinks/홍삼 인삼주" 에서 테스트 해보실 수 있습니다.
---
> ✨ Feat : 리뷰 무한스크롤 구현

- src/hooks/review/useReviewActions.ts
- src/utils/drink/action.ts
- src/utils/recommend/recommendationService.ts
🐛 Bug : 리뷰, 테마별 전통주, 드링크페이지 버그수정
---
---
1. 리뷰수정이 안되던 버그를 수정했습니다.
2. 테마별 전통주 추천할때 계절외에 카테고리는 난수로 정해지다 보니까
페이지 변경될때 카테고리도 변경되는 경우가 있었습니다. 
이 부분을 revalidate시간과 일치하도록 수정했습니다.
3. 드링크페이지에 접속시 에러가 뜨던 현상을 수정했습니다.
---
---
없습니다.
---
> 🐛 Bug : 리뷰, 테마별 전통주, 드링크페이지 버그수정

- src/app/drink/_components/ReviewContent.tsx
- src/app/drink/_components/ReviewEditingContent.tsx
- src/app/drink/_components/ReviewForm.tsx
- src/app/drink/_components/ReviewList.tsx
- src/app/drink/_components/ReviewStarRating.tsx
- src/hooks/review/useReviewActions.ts
- src/hooks/review/useReviewForm.ts
- src/types/review.ts
- src/utils/review/action.ts
- src/utils/review/textarea.ts
✨ Feat : 별점수정 구현
---
---
- 댓글 수정시 별점도 수정 되게 했습니다.
---
---
- 리뷰 등록시 별점이나 글자 수에 관한 에러 메시지를 실시간으로 나타나게 했습니다.
- 리뷰 수정시 글자 수에 관한 에러 메시지를 실시간으로 나타나게 했습니다.
---
> ✨ Feat : 별점수정 구현

- src/app/layout.tsx
- src/app/page.tsx
- src/app/place/[id]/page.tsx
- src/app/place/_components/Category.tsx
- src/app/place/_components/DetailSection.tsx
- src/app/place/_components/Information.tsx
- src/app/place/_components/KakaoMap.tsx
- src/app/place/_components/MainSection.tsx
- src/app/place/_components/Menu.tsx
- src/app/place/page.tsx
- src/components/common/BottomNavBar.tsx
- src/components/common/PlaceCard.tsx
- src/components/home/PlaceSection.tsx
- src/components/home/PopularDrinkSection.tsx
- src/components/recommend/ThematicRecommender.tsx
- src/types/drink.ts
- src/types/place.ts
- src/utils/drink/action.ts
- src/utils/place/action.ts
다이닝바 상세 페이지, 인기 전통주 및 다이닝바 목록  구현
---
---
- 다이닝바 상세 페이지 구현
- 홈 페이지에 들어갈 인기 전통주 및 다이닝바 목록 구현
---
---
- 잘 나오는지만 확인해주시면 될 것 같습니다.
---
> 다이닝바 상세 페이지, 인기 전통주 및 다이닝바 목록  구현

- src/app/drink/_components/ReviewList.tsx
- src/types/kakao.d.ts
🐛 Bug : kakao.d.ts type -> interface로 수정
---
---
- 인터페이스 확장성 때문에 다시금 롤백했습니다.
---
---
없습니다.
---
> 🐛 Bug : kakao.d.ts type -> interface로 수정

- src/app/mypage/_components/MyPageAccountOptions.tsx
- src/app/password/_components/EmailForm.tsx
- src/app/password/_components/PasswordForm.tsx
- src/app/password/check/page.tsx
- src/app/password/reset/page.tsx
- src/app/signin/_components/SignInForm.tsx
- src/hooks/auth/useCheckEmail.ts
- src/hooks/auth/useResetPassword.ts
- src/types/Auth.ts
- src/utils/auth/action.ts
- src/utils/supabase/admin.ts
회원 탈퇴 및 비밀번호 재설정 구현
---
---
- 회원 탈퇴 기능 구현
- 비밀번호 재설정 기능 구현
---
---
딱히 없습니다.
---
> 회원 탈퇴 및 비밀번호 재설정 구현

- src/app/layout.tsx
- src/app/mypage/_components/MyPageAccountOptions.tsx
- src/app/password/_components/PasswordForm.tsx
- src/app/signin/_components/SignInForm.tsx
- src/app/signup/_components/Information.tsx
- src/components/auth/UserInitializer.tsx
- src/hooks/auth/useCheckEmail.ts
- src/hooks/auth/useResetPassword.ts
- src/hooks/auth/useSignIn.ts
- src/hooks/auth/useSignUp.ts
- src/providers/AuthProvider.tsx
- src/utils/auth/action.ts
- src/utils/auth/manageError.ts
유저 정보 관리를 위해 Context API 추가하고 Auth 관련 부분 에러 처리
---
---
- 새로고침 등의 동작 시 유저 정보 잘 관리되도록 Context API 추가 적용
- Auth 관련 부분 에러 핸들링 처리
---
---
- Auth 관련 기능 중에 매끄럽지 않은 부분이 좀 있는데 디자인 작업하면서 틈틈이 보완해볼게요.
---
> 유저 정보 관리를 위해 Context API 추가하고 Auth 관련 부분 에러 처리

- tailwind.config.ts
🩹 Fix : tailwind.config.ts 파일수정
---
---
- 폰트 굵기 자동으로 적용 안되는것 수정했습니다.
---
---
없습니당.
---
> 🩹 Fix : tailwind.config.ts 파일수정

- src/app/mypage/_components/MyPagePreferences.tsx
✨ Feat : 내 취향정보 수정 링크
---
---
- 링크만 걸었습니다.
---
---
- 없습니다.
---
> ✨ Feat : 내 취향정보 수정 링크

- src/app/drink/_components/DrinkDescription.tsx
- src/app/drink/_components/DynamicHeader.tsx
- src/app/drink/_components/ReviewContent.tsx
- src/app/drink/_components/ReviewEditDeleteButtons.tsx
- src/app/drink/_components/ReviewEditingContent.tsx
- src/app/drink/_components/ReviewList.tsx
- src/app/drink/_components/ReviewReadOnlyContent.tsx
- src/app/layout.tsx
- src/hooks/review/useReviewActions.ts
- src/types/review.ts
- src/utils/review/action.ts
🐛 Bug : 리팩토링 과정에서 발생한 버그수정
---
---
- 공유하기와 관련된 파일 이동시켰습니다.
- 관련된 임포트 정상화시켰습니다.
- 다이나믹 헤더에 이름 길면 ...으로 되게 했습니다.
- 리뷰 관련 코드 리팩토링 후 발생한 버그 수정했습니다.
- 리뷰 타입을 테이블에서 가져오는것으로 바꿨는데 이 때, 관련 로직들의 컬럼명이 일치하지 않아 발생한 버그였습니다.
- 현재 수정됐고 DEV, BUILD 모두 확인했습니다.
---
---
이제 풀 받으셔도 됩니다!!!
---
> 🐛 Bug : 리팩토링 과정에서 발생한 버그수정

- src/app/drink/_components/DrinkImage.tsx
- src/app/drink/_components/ReviewActionButtons.tsx
- src/app/drink/_components/ReviewContent.tsx
- src/app/drink/_components/ReviewEditingContent.tsx
- src/app/drink/_components/ReviewForm.tsx
- src/app/drink/_components/ReviewList.tsx
- src/components/common/ProductCard.tsx
- src/hooks/review/useReviewEditing.ts
- src/hooks/review/useReviewForm.ts
- src/types/review.ts
- src/utils/review/textarea.ts
- tailwind.config.ts
리뷰 에러메시지 제거, 스타일 수정
---
---
- 임의대로 구현한 에러메세지 제거했습니다.
- 관련로직도 제거했습니다. 
- 이제 등록/수정시 에러메세지가 아닌 버튼이 비활성화 됩니다.
---
---
`tailwind.config.ts` : 보더관련 로직 삭제 후 radius에 문제 없나 테스트 한 번 해보세용.
---
> 리뷰 에러메시지 제거, 스타일 수정

- src/app/search/_components/FilterModal.tsx
- src/app/search/_components/RecommendCategory.tsx
- src/app/search/_components/SelectSorted.tsx
- src/app/search/page.tsx
- src/styles/globals.css
문제점 2가지 추가 수정
팀원분께 테스트 통해 받은 문제점 해결
---
---
1. 가나다순 -> 이 부분은 supabase에서 확인해야해서 미해결
2. 추천 검색어 클릭시 바로 검색 적용
3. 스크롤바 지우기
---
---
1. 가나다순은 우선은 기본순으로 정렬하였습니다.
2. usePathname으로 다른 링크로 벗어났을 때 search 초기화는 MVP 이후에 작업하겠습니다.
---
> 🐛 오류 사항 수정 : 문제점 2가지 수정

- src/app/mypage/_components/ProfileEditModal.tsx
- src/components/auth/UserInitializer.tsx
- vercel.json
💄 Style : 닉네임 중복검사 에러메시지 수정
---
---
- 피그마대로...
---
---
없습니다.
---
> 💄 Style : 닉네임 중복검사 에러메시지 수정

- src/app/drink/_components/ReviewContent.tsx
- src/app/layout.tsx
- src/app/mypage/_components/MyPageProfileSection.tsx
- src/app/page.tsx
- src/components/common/BottomNavBar.tsx
- src/components/common/Modal.tsx
- src/components/common/ProductCard.tsx
- src/components/common/ScrollTop.tsx
- src/utils/recommend/action.ts
🩹 Fix : 추천 주류갯수 수정
---
---
- 추천 주류 갯수 수정했습니다.
- 디자인 피드백 반영했습니다.
- 바텀네비바
- 스크롤탑버튼
- 메타데이터
- 최대 가로길이
---
---
없습니다 간단합니다.
---
> 🩹 Fix : 추천 주류갯수 수정

- src/app/search/_components/FilterModal.tsx
- src/app/search/_components/FilterSideBar.tsx
- src/app/search/_components/SearchWrap.tsx
- src/app/search/_components/SelectSorted.tsx
- src/hooks/search/useFilterSortedResults.ts
- src/hooks/search/useSearchSortedResults.ts
- src/styles/globals.css
가나다순 정렬 수정 + slideBar 수정
---
---
기본 순에서 가나다순 정렬로 수정
슬라이드 바 필터버튼이 전체 width 가지는 문제 수정ing
---
---
Swiper에 class 직접적으로 주기보다 속성이 포함되어있어서
만약 class 변경 테스트 해보고 싶으시다면  wrapperClass에 class 추가해주시면 됩니다.
---
> 🐛 검색결과 :  가나다순 정렬 수정 + slideBar 수정

- src/app/page.tsx
- src/app/survey/_components/ProgressBar.tsx
- src/app/survey/_components/StepButton.tsx
- src/app/survey/page.tsx
- src/components/common/BottomNavBar.tsx
- src/components/home/AfterBanner.tsx
- src/components/home/Banner.tsx
- src/components/home/BeforeBanner.tsx
취향조사 버튼 비활성화 스타일 개선, 배너 크기 변경
---
---
취향조사 버튼 비활성화 스타일 개선, 배너 크기 변경
---
---
---
> 취향조사 버튼 비활성화 스타일 개선, 배너 크기 변경

- src/app/page.tsx
- src/app/search/_components/FilterSideBar.tsx
- src/app/search/_components/HomeScreenButton.tsx
- src/app/search/_components/ResultList.tsx
- src/app/search/_components/SearchBar.tsx
- src/app/search/_components/SearchWrap.tsx
---
---
발표시 문제되는 w-375 -> w-full 로 변경함
---
---
당장 w-full을 사용했기에 발표 이후 수정해야될 가능성 있음.
---
> 🐛 발표 디자인 수정 

- src/app/search/_components/FilterModal.tsx
버튼 어긋난 부분 수정
---
---
버튼 스타일링 어긋나서 수정
---
---
button 감싸는 div w-full로 아래 보이는 문제 수정
---
> 🐛 버튼 스타일링:

- src/app/like/page.tsx
- src/app/mypage/_components/MyPageComponent.tsx
- src/app/mypage/_components/MyPagePreferences.tsx
- src/hooks/mypage/useMyPage.ts
- src/utils/preference/action.ts
---
---
좋아요 페이지 재정렬하고, 마이페이지 수정배너 설문조사 미참여자랑 참여자 각각 link 경로 다르게 설정
---
---
---
> 좋아요 페이지 재정렬, 마이페이지 수정배너 link 다르게 설정

- src/app/drink/_components/DrinkBasicInfo.tsx
- src/app/drink/_components/DrinkDescription.tsx
- src/app/drink/_components/DrinkDetail.tsx
- src/app/drink/_components/DrinkTasteProfile.tsx
- src/components/home/ThematicRecommender.tsx
- src/types/drink.ts
🩹 Fix : Drink타입 통일
---
---
- 류제천 튜터님 피드백 반영했습니다.
- 저만 사용하는거긴 한데 src/types/drink.ts에 몇 가지 추가한게 있습니다.
---
---
없습니다.
---
> 🩹 Fix : Drink타입 통일

- src/app/search/_components/RecommendCategory.tsx
- src/app/search/_components/ResultList.tsx
- src/app/search/_components/Skeleton.tsx
- src/app/search/_components/TotalAndSort.tsx
💄 반응형 : 반응형 업데이트 + 에러 처리
---
---
1. UT 환경에서 동작할 수 있는 반응형 수정
2. queryKey 삭제 안되는 문제 수정
---
---
Search 폴더 내부의 Skeleton , Result list의 91번째 문단 참고하시면 됩니다.
---
> 💄 반응형 : 반응형 업데이트 + 에러 처리

- src/components/common/ShareButton.tsx
- src/hooks/like/useMultipleLike.ts
🩹 Fix : 공유하기 토스트팝업 수정
---
---
- 공유하기 버튼의 토스트 팝업 수정을 놓쳤습니다.
---
---
- 깰꼼
---
> 🩹 Fix : 공유하기 토스트팝업 수정

- public/assets/icons/Radio-Button-clicked.svg
- public/assets/icons/Radio-Button.svg
- public/assets/icons/cancel-primary.svg
- public/assets/icons/search-gray.svg
- src/app/search/_components/AlcholStrength.tsx
- src/app/search/_components/AlcholTaste.tsx
- src/app/search/_components/FilterModal.tsx
- src/app/search/_components/FilterSideBar.tsx
- src/app/search/_components/FocusInput.tsx
- src/app/search/_components/HomeScreenButton.tsx
- src/app/search/_components/RecommendCategory.tsx
- src/app/search/_components/SearchBar.tsx
- src/app/search/_components/SearchWrap.tsx
- src/app/search/_components/StandByScreen.tsx
- src/app/search/_components/_ui/DualRangeSliderProps.tsx
- src/components/common/OptimizedImage.tsx
- src/store/focusStore.ts
- src/styles/globals.css
디자인 피드백 반영 , Image -> 공통 컴포넌트로 변경
---
---
디자인 피드백 반영 , Image 컴포넌트 공용 컴포넌트로 사용
---
---
혹시라도 LF 문제가 났을 때 한번 브리핑 해주시면 감사하겠습니다
체크하고, svg 상에서 문제가 없을 때 push 했습니다.
---
> 💄 Style 수정 : 공통 컴포넌트 사용

- .gitignore
- next.config.mjs
- package.json
- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- src/app/api/sentry-example-api/route.ts
- src/app/drink/_components/DrinkDescription.tsx
- src/app/drink/_components/DrinkSection.tsx
- src/app/drink/_components/DynamicHeader.tsx
- src/app/global-error.tsx
- src/app/mypage/_components/MyPageAccountOptions.tsx
- src/app/mypage/error.tsx
- src/app/not-found.tsx
- src/app/sentry-example-page/page.tsx
- src/components/common/ErrorComponent.tsx
- src/instrumentation.ts
- src/types/errorTypes.ts
- yarn.lock
✨ Feat : sentry연동
---
---
- 센트리 연동
- 에러컴포넌트 생성
- 글로벌에러 생성 (자동)
- 404 생성
---
---
- pull 받으시고  yarn 하셔야 합니다.
- error.tsx 갖다 쓰시면 됩니다.
---
> ✨ Feat : sentry연동

- src/app/drink/[id]/page.tsx
- src/app/drink/_components/DrinkSection.tsx
🐛 Bug : 주류 상세페이지 에러핸들링 수정
---
---
- 주류 상세페이지 에러핸들링 구현
---
---
센트리 키 슬랙에 올려놨습니다.
.env에 추가하세요.
---
> 🐛 Bug : 주류 상세페이지 에러핸들링 수정

- src/app/place/[id]/error.tsx
- src/app/signin/_components/Social.tsx
- src/hooks/auth/useCheckEmail.ts
- src/hooks/auth/useResetPassword.ts
- src/hooks/auth/useSignIn.ts
- src/hooks/auth/useSignUp.ts
auth 및 place 관련 부분에 Sentry 연결
---
---
- auth 및 place 관련 부분에 Sentry 연결
---
---
딱히 업습니다
---
> auth 및 place 관련 부분에 Sentry 연결

- src/app/actions/recommend.ts
✨ Feat : openAI 에러핸들링
---
---
- opanAI 에러핸들링 추가했습니다.
---
---
- 없습니다.
---
> ✨ Feat : openAI 에러핸들링

- src/app/actions/filter.ts
- src/app/search/_components/FilterModal.tsx
- src/app/search/_components/ResultList.tsx
- src/app/search/_components/SearchBar.tsx
- src/app/search/_components/SearchWrap.tsx
- src/app/search/error.tsx
- src/app/search/page.tsx
🐛 필터 뒤로가기 수정
---
---
필터를 진행했을 때 뒤로 가기가 먹히지 않아서,
query를 작성하여서 필터 했을 때에도 상세 정보 넘어갔을 때?
뒤로 가기를 누르면 이전 기록으로 넘어가게 수정하였습니다.
(검색도 마찬가지)
그리고 error.tsx 던져졌을 때 동작되는지 체크했습니다.
---
---
뒤로 가기에 문제가 있을 시에 말씀해주세요.
현재는 param으로 체크해서 다른 페이지를 다녀왔을 때만 확인하고,
query가 다를 때만 정보가 기억되고 있기 때문에 플로우 상 에러가 있을 수 있습니다.
---
> 🐛 필터 뒤로가기 수정 : 뒤로가기 설정 추가 + error.tsx 추가

- src/app/search/_components/FilterModal.tsx
- src/app/search/_components/RecommendCategory.tsx
추천 검색어 눌렀을 때 query 생성
---
---
추천 검색어를 누르고 검색을 들어갔을 때,
url 에 query가 생성되지 않아 뒤로가기가 비활성화 되어 있었음
-> 그 문제 뒤로가기 가능하게 변경
---
---
router.path에 현재까지 문제는 발견되지 않았지만
뒤로가기 문제 발견시 router.path에 문제가 있을듯
---
> 🐛 추천 검색어 : 눌렀을 때 query 생성

- src/hooks/mypage/useProfileEdit.ts
🩹 Fix : 프로필 이미지 한글도 업로드 되게 수정
---
---
- 프로필 이미지 한글이름도 수정됩니다.
---
---
- 없습니다.
---
> 🩹 Fix : 프로필 이미지 한글도 업로드 되게 수정

- src/app/preferences/result/_components/DrinkList.tsx
⚰️ Chore : 불필요한 코드제거
---
---
⚰️ Chore : 불필요한 코드제거
---
---
---
> ⚰️ Chore : 불필요한 코드제거

- src/app/like/_components/LikesContent.tsx
- src/app/preferences/result/_components/DrinkList.tsx
- src/app/search/_components/ResultList.tsx
- src/components/common/ProductCard.tsx
- src/components/home/ThematicRecommender.tsx
- src/styles/globals.css
💄 Style : ProductCard 반응형 구현
---
---
- ProductCard 반응형 구현했습니다.
- 빌드 테스트 때문에 수정한 컴포넌트가 있습니다.
- 수정된 코드 보시고 참고하시면 됩니다. 
---
---
- 테마별 전통주 컴포넌트도 같이 했는데, 심신미약으로 완벽하지 않을 수 있습니다.
---
> 💄 Style : ProductCard 반응형 구현

- src/app/actions/mypage.ts
- src/app/drink/[id]/page.tsx
- src/app/drink/_components/DrinkTasteProfile.tsx
- src/app/layout.tsx
- src/app/mypage/_components/ProfileEditModal.tsx
- src/app/mypage/_components/ProfileImageUpload.tsx
- src/components/common/Modal.tsx
- src/components/common/ShareModal.tsx
- src/components/common/Toast.tsx
- src/components/layout/HeaderClient.tsx
- src/hooks/mypage/useProfileEdit.ts
💄 Style : 모달, 토스트, 공유하기모달 수정 외
---
---
- 공통레이아웃 mt-[102px]
- 헤더 fixed때문에 헤더높이만큼 mt추가했습니다.
- 모달 디자인
- 토스트 개행되는거 수정
- 프로필 이미지 삭제 구현했습니다.
---
---
- 헤더는 search들어가면 색상변합니다.
---
> 💄 Style : 모달, 토스트, 공유하기모달 수정 외

- src/app/drink/[id]/page.tsx
- src/app/drink/_components/DrinkBasicInfo.tsx
- src/app/drink/_components/DrinkDetailNavigator.tsx
- src/app/drink/_components/DrinkImage.tsx
- src/app/drink/_components/DrinkTasteProfile.tsx
- src/app/drink/_components/FoodPairing.tsx
- src/app/drink/_components/ReviewList.tsx
- src/app/drink/_components/ReviewSection.tsx
- src/app/mypage/_components/MyPageAccountOptions.tsx
- src/app/mypage/_components/MypageModal.tsx
- src/components/common/Modal.tsx
- src/components/common/ProductCard.tsx
- src/components/layout/Footer.tsx
- src/components/layout/HeaderClient.tsx
- src/components/layout/LoggedInMenu.tsx
💄 Style : 주류 상세페이지 디자인 반영 외
---
---
- 주류 상세페이지 디자인 반영했습니다.
- 마이페이지 모달 구현했습니다.
---
---
아직 해결못한부분
- 노트북에서 스크롤 내리면 주류 사진이 반쯤 가려짐 (가려지면 안됨)
- 데스크탑에서 URL로 /mypage 접속시 차단이나 리다이렉트
- 미들웨어에서 시도해봤는데 완전차단돼서 리서치 좀 해봐야됨
---
> 💄 Style : 주류 상세페이지 디자인 반영 외

- src/app/drink/[id]/page.tsx
- src/app/drink/_components/ReviewSection.tsx
- src/app/page.tsx
💄 Style : 홈 페이지, 주류 상세페이지 margin조정
---
---
- 루트레이아웃 mb-32 유지시에 margin값 조정했습니다.
---
---
디자이너님들 피드백 후 루트 레이아웃 마진 조정되어야 하면 그 때 다시 수정할게요.
---
> 💄 Style : 홈 페이지, 주류 상세페이지 margin조정

- public/assets/icons/back_gray.svg
- public/assets/icons/back_place.svg
- src/app/place/[id]/page.tsx
- src/components/auth/Button.tsx
- src/components/auth/CheckField.tsx
- src/components/common/OptimizedImage.tsx
다이닝바 상세 페이지 디자인 보완
---
---
- 다이닝바 상세 페이지 디자인 보완
---
---
딱히 없어요
---
> 다이닝바 상세 페이지 디자인 보완

- src/app/drink/[id]/page.tsx
- src/app/drink/_components/ReviewSection.tsx
- src/app/layout.tsx
- src/app/page.tsx
- src/components/home/PlaceSection.tsx
💄 Style : 아래간격 재조정, 프로그래스바
---
---
- 폰트 프리로드 했습니다.
- 마진 제대로 조정했습니다.
---
---
없습니다.
---
> 💄 Style : 아래간격 재조정, 프로그래스바 외

- src/app/search/_components/FilterModal.tsx
- src/app/search/_components/_ui/Select.tsx
- src/components/common/OptimizedImage.tsx
💄 Image 컴포넌트 교체 : 컴포넌트로 교체
---
---
팀에서 합의한 Image 컴포넌트 OptimizedImage 컴포넌트로 교체
(미처 확인하지 못한 부분 수정)
---
---
없습니다!
---
> 💄 Image 컴포넌트 교체 : 컴포넌트로 교체

- src/app/layout.tsx
- src/components/layout/HeaderClient.tsx
💄 Style : 헤더 fixed로 수정
---
---
- 헤더 고정 fixed로 수정했습니다.
- 서치 페이지에서 스크롤 내리면 색상 바뀌게 수정했습니다.
---
---
없습니다.
---
> 💄 Style : 헤더 fixed로 수정

- src/app/layout.tsx
- src/app/place/_components/KakaoMap.tsx
지도가 제대로 로드되지 않는 문제 해결
---
---
- yarn build 하고 최초 방문 시 지도가 제대로 로드되지 않는 문제 해결
---
---
yarn build 하고 최초 방문 시 지도가 로드되지 않고 새로고침해야 로드되는 문제가 발견되어서 해결했습니다. 로컬에서는 해결된 것처럼 보이는데 배포한 뒤에 배포 링크에서 한 번 더 확인하는 과정 필요할 것 같습니다.
---
> 지도가 제대로 로드되지 않는 문제 해결

- src/app/mypage/page.tsx
- src/app/password/check/page.tsx
- src/components/common/MobilePageGuardProvider.tsx
- src/hooks/common/useMobilePageGuard.ts
✨ Feat : 데스크탑에서 URL 접속차단
---
---
- 데스크탑에서 URL 직접 접속시 [/mypage, /password/check] 페이지 차단했습니다.
---
---
- 미들웨어에서 구현이 불가능하다고 합니다.
그래서 커스텀 훅으로 만들고 감싸줬습니다.
---
> ✨ Feat : 데스크탑에서 URL 접속차단

- src/app/actions/auth.ts
- src/app/mypage/_components/MyPageAccountOptions.tsx
- src/app/password/_components/EmailForm.tsx
- src/hooks/auth/useResetPassword.ts
auth 관련 버그 수정
---
---
- 로그인하지 않은 상태에서 비밀번호 재설정을 할 경우, 완료 후 로그인 페이지로 이동
- 회원 탈퇴 로직 수정
---
---
제천튜터님께서 회원 탈퇴 기능은 굳이 완료될 때까지 기다릴 필요없이 백그라운드에서 처리하고 사용자한테는 빠르게 완료된 것처럼 보여주면 된다고 하셔서 저번에 수정했었는데 로직이 매끄럽지 않아서 순서만 조금 변경했습니다.
---
> auth 관련 버그 수정

- src/app/drink/_components/DrinkDescription.tsx
- src/app/drink/_components/DrinkImage.tsx
- src/app/drink/_components/DynamicHeader.tsx
- src/app/drink/_components/ReviewEditingContent.tsx
- src/app/drink/_components/ReviewLoginPrompt.tsx
- src/app/drink/_components/ReviewReadOnlyContent.tsx
- src/app/mypage/_components/MyPageAccountOptions.tsx
- src/app/mypage/_components/MyPageHeader.tsx
- src/app/mypage/_components/MyPagePreferences.tsx
- src/app/mypage/_components/ProfileImageUpload.tsx
- src/app/mypage/_components/ProfileNicknameInput.tsx
- src/components/common/BackButton.tsx
- src/components/common/Toast.tsx
💄 Style : 1차 디자인 시안 추가반영
---
---
- 주류 상세페이지 수정
- 주류 이미지 border 수정
- 다이나믹 헤더 조정
- 크기 및 간격조정
- 스크롤 수치 수정
- 리뷰 컴포넌트 수정
- 마이페이지 수정
- 색상수정 및 UT반영
- 이미지 삭제 버튼 항상 보이게 수정
- 뒤로가기 버튼 수정
- 배경생성
- 토스트 피드백 반영
---
---
body에 text-grayscale-900 입혀놔서 편합니다.
---
> 💄 Style : 1차 디자인 시안 추가반영

- src/app/drink/_components/FoodPairing.tsx
- src/components/common/Modal.tsx
- src/components/common/OptimizedImage.tsx
- src/components/common/PlaceCard.tsx
- src/components/home/AfterBannerDesktop.tsx
- src/components/home/BeforeBannerDesktop.tsx
💄 Style : 디자인 QA 반영
---
---
- OptimizedImage : 감싸고 있던 div태그 제거
- 필요에 따른 부모요소에 relative추가
- chevron-right : 인클루드 속성 때문에 강제로 width지정 (데스크탑에서 보일 배너)
- 모달 디자인 QA반영
---
---
- 없습니다.
---
> 💄 Style : 디자인 QA 반영

- src/app/mypage/_components/MyPageAccountOptions.tsx
- src/app/password/_components/EmailForm.tsx
- src/app/password/_components/PasswordForm.tsx
- src/app/signin/_components/OptionLink.tsx
- src/app/signin/_components/SignInForm.tsx
- src/app/signin/_components/Social.tsx
- src/app/signup/_components/SignUpForm.tsx
- src/components/auth/ConfirmModal.tsx
- src/hooks/auth/useConfirmModal.ts
auth 관련 모달을 커스텀 훅으로 분리
---
---
- auth 관련 모달을 커스텀 훅으로 분리
---
---
없습니다.
---
> auth 관련 모달을 커스텀 훅으로 분리

- src/app/actions/filter.ts
- src/app/api/drink/route.ts
- src/app/search/_components/AlcholStrength.tsx
- src/app/search/_components/AlcholType.tsx
- src/app/search/_components/FilterModal.tsx
- src/app/search/_components/FilterSideBar.tsx
- src/app/search/_components/FocusInput.tsx
- src/app/search/_components/RecommendCategory.tsx
- src/app/search/_components/ResultList.tsx
- src/app/search/_components/SearchBar.tsx
- src/app/search/_components/SearchLogo.tsx
- src/app/search/_components/SearchWrap.tsx
- src/app/search/_components/SelectSorted.tsx
- src/app/search/_components/_ui/DualRangeSliderProps.tsx
- src/app/search/page.tsx
- src/hooks/search/useFilterSortedResults.ts
- src/hooks/search/useLikedResults.ts
- src/hooks/search/useSearchSortedResults.ts
- src/utils/filter/generateUrl.ts
- src/utils/filter/queryParamsUtils.ts
♻️ Search 코드 리팩토링 : URL 이용
---
---
검색 히스토리가 필요하여서 URL 검색으로 진행
---
---
현재 sort에서 좋아요 부분과, 검색창 추천검색어 버튼 누르면 이동이 되지 않을겁니다.
고 부분을 제외하고는 디자인 QA 반영되어 있어서 PR 올립니다!
---
> ♻️ Search 코드 리팩토링 : URL 이용

- src/app/password/_components/PasswordForm.tsx
- src/app/signup/_components/SignUpForm.tsx
- src/hooks/auth/useResetPassword.ts
- src/hooks/auth/useSignIn.ts
- src/utils/auth/manageError.ts
auth 관련 에러 핸들링 보완
---
---
- 로그인 및 회원가입 관련 에러 핸들링 보완
- 비밀번호 재설정 관련 에러 핸들링 추가
---
---
없습니다.
---
> auth 관련 에러 핸들링 보완

- src/app/layout.tsx
head에 불필요한 스크립트 제거
---
---
head에서 service-worker 스크립트 제거
---
---
---
> head에 불필요한 스크립트 제거

- src/app/drink/_components/DrinkInfoRow.tsx
- src/app/drink/_components/TasteProfileRow.tsx
- src/constants/tasteProfileColors.ts
- src/utils/drink/formatValue.ts
🩹 Fix : 피드백 반영
---
---
- 피드백 반영입니다.
---
---
- 없습니다.
---
> 🩹 Fix : 피드백 반영

- src/app/mypage/_components/MyPageAccountOptions.tsx
- src/components/common/Modal.tsx
모달 margin 수정
---
---
- 모달 margin 수정
---
---
공통 모달 margin이 다르게 되어 있어서 수정했습니다.
---
> 모달 margin 수정

- src/app/layout.tsx
- src/app/manifest.ts
💄 Style : safari 상단바 색상변경
---
---
- 진짜 변경했습니다.
- 범인도 찾았습니다.
---
---
---
> 💄 Style : safari 상단바 색상변경

- src/app/place/_components/MainSection.tsx
- src/components/common/PlaceCard.tsx
다이닝바 이미지 최적화 설정 및 디자인 QA 반영
---
---
- 다이닝바 이미지 최적화 위한 설정
- 데스크탑인 경우 다이닝바 메인 이미지에 border-radius 추가
---
---
없습니다.
---
> 다이닝바 이미지 최적화 설정 및 디자인 QA 반영

- src/components/home/ThematicRecommender.tsx
🩹 Fix : 프리로드 영역수정
---
---
- 프리로드 영역수정했습니다.
---
---
---
> 🩹 Fix : 프리로드 영역수정

- public/service-worker.js
- src/app/actions/filter.ts
♻️ Supabase 검색 로직 수정 : 여백없이 검색 가능
---
---
가평 생 막걸리 -> 가평생막걸리 검색 가능하게 수정
---
---
우선은 수정하면서 supabase 에서 가능한 방법이 컬럼 생성이여서
컬럼으로 진행했습니다.
---
> ♻️ Supabase 검색 로직 수정 : 여백없이 검색 가능
